version: 0.2

phases:
  build:
    commands:
      - echo start build at `date`
      - ./gradlew test
reports:
  junit-sample-report:
    files:
      - '**/*'
    base-directory: build/reports/tests/
    discard-paths: no