version: 0.2

phases:
  build:
    commands:
      - echo start build at `date`
      - ./gradlew test
      - ls -la build/test-results/test
reports:
  junit-sample-report:
    files:
      - '*'
    base-directory: build/test-results/test
    discard-paths: no
